### ISSUE TITLE
Is it `waitFor` logic not necessary for Redux?

### ISSUE THREAD

**Issue by mocheng** [d6u/redux-chat#1]
Thanks for this demo code. This counterpart of Flux-chat is what I'm looking for.

However, the code is misleading and made me suppose that `thunk` is the counterpart of `waitFor` in Flux. I changed mind after several kinds of code review.

In my understanding, there is no need of `waitFor` counterpart in Redux since there is only one store. In flux-chat, there is one `UnreadCountStore` whose state is the unread count. This `UnreadCountStore` waits for  `ThreadStore` since its store value depends on state of `ThreadStore`. In Redux, unread count is not stored in store, but calculated in component based on State.

The introduction of  `thunk` is to make this redux-chat demo AJAX-like IO feature, right? This is kind of feature is not in flux-chat.

Is my understanding correct?

Some explanation of this code base will help.
Thank you very much!

**Comment by d6u** [comment]
@mocheng Glad that this example is useful to you. Notice the codebase is kinda old, so I cannot fully remember the details.

However, I don't think `thunk` is equivalent to `waitFor` here. Redux has no `waitFor` equivalent in its concept and you are right that there is no need for `waitFor` in Redux. 

Yes, the official Facebook flux example doesn't have async IO, but I recreated [their example](https://github.com/d6u/flux-chat) to simulate AJAX like async action -> https://github.com/d6u/flux-chat/blob/master/js%2Futils%2FChatWebAPIUtils.js#L23-L25.
